// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Template.Models.Sql.Models
{
    public partial class TemplateTable
    {
        public long Id { get; set; }
        public string Description { get; set; }
    }
}